#! /usr/bin/env python3

import sys, pdb, numpy as np
from ibex import IBEX

if len(sys.argv) == 1 or sys.argv[1] == '-h':
  print("Usage: %s in.ibx lower upper maxo out.ibx" % sys.argv[0])
  sys.exit(1)

idata = sys.argv[1]
lower = int(sys.argv[2])
upper = int(sys.argv[3])
maxo = float(sys.argv[4])
oname = sys.argv[5]

def bracket(ibx):
  v = ibx.Variable('exposure_time')
  return np.where(v < lower, maxo, np.where(v > upper, 0, maxo * (v - upper) / (lower - upper)))
  
ibex = IBEX.Read(sys.argv[1])
ibex.Calculate('bracket_%d_%d_%3.2f' % (lower, upper, maxo), bracket)
ibex.Write(oname)


