#! /usr/bin/env python3

import sys, pdb
from ibex import IBEX

def syntax(a):
  print('syntax: ', a, ' csv [csv...] {outfile}')
  sys.exit(1)

directory = None

csvs = sys.argv[1:-1]
outfile = sys.argv[-1]

if len(csvs) == 0 or not outfile:
  syntax(sys.argv[0])

ibex = IBEX()

for csv in csvs:
  ibex.AddFromCSV(csv)

ibex.Sort()

ibex.Write(outfile)





