#! /usr/bin/env python3

import sys, pdb
from ibex.ibex import IBEX
from glob import glob

def syntax(a):
  print('syntax:', a, '{directory} {outfile}')
  sys.exit(1)

if len(sys.argv) != 3:
  syntax(sys.argv[0])

ibex = IBEX()

for csv in glob('%s/*csv' % sys.argv[1]):
  print(csv)
  ibex.AddFromCSV(csv)


ibex.Write(sys.argv[2])





