#! /usr/bin/env python3

import sys, pdb
from ibex import IBEX
from glob import glob

def syntax(a):
  print('syntax:', a, 'options {directory} {outfile}')
  print('options:')
  print('  -p pattern    glob pattern in source directory (*.csv)')
  sys.exit(1)

directory = None
outfile = None
pattern = '*.csv'

args = sys.argv[1:]
while len(args) > 0:
  if args[0] == '-p':
    pattern = args[1]
    args = args[2:]
  elif not directory:
    directory = args[0]
    args = args[1:]
  elif not outfile:
    outfile = args[0]
    args = args[1:]
  else:
    syntax(sys.argv[0])

if not directory or not outfile:
  syntax(sys.argv[0])

ibex = IBEX()

for csv in sorted(glob('%s/%s' % (directory, pattern))):
  ibex.AddFromCSV(csv)

ibex.Write(outfile)





