#! /usr/bin/env python3

import sys, pdb, numpy as np, os
from tkinter import filedialog
from tkinter import *
from tkinter.ttk import Separator
from PIL import Image, ImageTk
from ibex import IBEX
import colortools as ct
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

class Application(Frame):

    def update2D(self):
        if self.varname and self.errname:
          f = (1023*self.normalized_var).astype('u2')
          e = (1023*self.err).astype('u2')
          rgb = (255*self.TwoDCmap[f,e]).astype('u1')
          img = Image.fromarray(rgb).resize((720,360))
          tkimg = ImageTk.PhotoImage(img)
          self.resultImage.configure(image=tkimg, height=360, width=720)
          self.resultImage.image = tkimg

    def selectDataset(self, a):
        ds = self.currentDataset.get()
        indx = self.ibx.names.index(ds)
        self.updateTimestep(indx)

    def next(self):
        if self.current_index == (len(self.ibx.names)-1):
          self.updateTimestep(0)
        else:
          self.updateTimestep(self.current_index + 1)

    def prev(self):
        if self.current_index == 0:
          self.updateTimestep(len(self.ibx.names)-1)
        else:
          self.updateTimestep(self.current_index - 1)

    def update1D(self, v, label, cmap):
        iv = (255*v).astype('u2')
        cv = (255*cmap[iv]).astype('u1')
        img = Image.fromarray(cv).resize((540,270))
        tkimg = ImageTk.PhotoImage(img)
        label.configure(image=tkimg, height=270, width=540)
        label.image = tkimg

    def newDataVar(self, d, update_ui):
        self.varname = d
        n,varnames,vardata = self.ibx.GetByIndex(self.current_index)
        self.var = vardata[varnames.index(self.varname)]
        if np.min(self.var) != 0 or np.max(self.var) != 1:
          self.normalized_var = (self.var - np.min(self.var)) / (np.max(self.var) - np.min(self.var))
        else:
          self.normalized_var = self.var
        if update_ui:
          self.updateVar()
          self.update2D()
        
    def newErrorVar(self, e, update_ui):
        self.errname = e
        n,varnames,vardata = self.ibx.GetByIndex(self.current_index)
        self.err = vardata[varnames.index(self.errname)]
        if update_ui:
          self.updateErr()
          self.update2D()
        
    def updateTimestep(self, indx):
        n,varnames,vardata = self.ibx.GetByIndex(self.current_index)
        if self.varname:
          self.var = vardata[varnames.index(self.varname)]
          if np.min(self.var) != 0 or np.max(self.var) != 1:
            self.normalized_var = (self.var - np.min(self.var)) / (np.max(self.var) - np.min(self.var))
          else:
            self.normalized_var = self.var
        if self.errname:
          self.err = vardata[varnames.index(self.errname)]
        self.current_index = indx
        self.updateGUI()

    def updateVar(self):
        if self.varname:
          self.update1D(self.normalized_var, self.varImage, self.varCmap)
          self.var_histo_plot1.clear()
          self.var_histo_plot1.hist(self.var.flatten(), bins=30)
          self.histo_canvas.draw()

    def updateErr(self):
        if self.errname:
          self.update1D(self.err, self.errImage, self.errCmap)
          self.err_histo_plot1.clear()
          self.err_histo_plot1.hist(self.err.flatten(), bins=30)
          self.histo_canvas.draw()

    def updateGUI(self):
        self.updateVar()
        self.updateErr()
        self.update2D()
        self.update2DCmap()
        self.updateHistos()
        self.currentDataset.set(ibx.names[self.current_index])

    def ChooseVarCmap(self):
        filename = filedialog.askopenfilename(initialdir=os.getcwd(),
                        title = "Select a colormap",
                        filetypes = (("1D map files", "*.csv *.json *.xml"), ("all files", "*.*")))
        if filename != '':
          self.varCmapWidget.configure(text=filename)
          self.varCmap = ct.load_colormap(filename)
          self.updateVar()

    def ChooseErrorCmap(self):
        filename = filedialog.askopenfilename(initialdir = os.getcwd(),
                        title = "Select a colormap",
                        filetypes = (("1D map files", "*.csv *.json *.xml"), ("all files", "*.*")))
        if filename != '':
          self.errCmapWidget.configure(text=filename)
          self.errCmap = ct.load_colormap(filename)
          self.updateErr()

    def Choose2DCmap(self):
        filename = filedialog.askopenfilename(initialdir = os.getcwd(),
                        title = "Select a colormap",
                        filetypes = (("2D map files", "*.cmap2D"), ("all files", "*.*")))
        if filename != '':
          self.TwoDCmap = ct.ReadColormap2D(filename)
          self.TwoDCmapName = filename.split('/')[-1].split('.')[0]
          self.TwoDCmapWidget.configure(text=filename)
          self.update2DCmap()
          self.update2D()

    def update2DCmap(self):
        rgb = (255*self.TwoDCmap).astype('u1')
        img = Image.fromarray(np.flip(rgb, axis=0)).resize((256,256))
        tkimg = ImageTk.PhotoImage(img)
        self.cmap2D_image.configure(image=tkimg, height=256, width=256)
        self.cmap2D_image.image = tkimg

    def Save(self):
        f = (1023*self.current_var).astype('u2')
        e = (1023*self.current_err).astype('u2')
        rgb = (255*self.TwoDCmap[f,e]).astype('u1')
        img = Image.fromarray(rgb)
        img.save('%s-%s.png' % (self.currentDataset.get(), self.TwoDCmapName))
        
    def SaveAll(self):
        directory = filedialog.askdirectory(initialdir = os.getcwd(), title = "Select output directory")
        for i in range(len(self.ibx.names)):
          dataset_name,varnames,vardata = self.ibx.GetByIndex(i)
          f = (1023*vardata[varnames.index(self.varname)]).astype('u2')
          e = (1023*vardata[varnames.index(self.errname)]).astype('u2')
          rgb = (255*self.TwoDCmap[f,e]).astype('u1')
          img = Image.fromarray(rgb).resize((720,360))
          img.save('%s/%s.png' % (directory, dataset_name))
        
    def Quit(self):
        print('Quit')


    def Setup(self):
        self.grid()
        self.master.title("IBEX Viewer")

        f = Frame(self.master)
        f.grid(row=0, column=0, columnspan=2)
        
        Label(f, text="Signal").pack(side=LEFT)

        self.varString = StringVar(f)
        self.varString.set("Select...")
        sigmenu = OptionMenu(f, self.varString, *self.ibx.varnames, command=lambda value: self.newDataVar(value, True))
        sigmenu.pack(side=LEFT)

        self.varImage = Label(self.master)
        self.varImage.grid(row=1, column=0, columnspan=2)

        f = Frame(self.master)
        f.grid(row=2, column=0, columnspan=2, sticky='ewns')

        a = Label(f, text='1D Colormap: ').pack(side=LEFT)

        self.varCmapWidget = Label(f, text='GreyScale')
        self.varCmapWidget.pack(side=LEFT)

        b = Button(f, text="...", command=self.ChooseVarCmap)
        b.pack(side=LEFT)

        hgap = Separator(self.master, orient='horizontal').grid(row=3, column=0, columnspan=2, sticky='ew')

        f = Frame(self.master)
        f.grid(row=4, column=0, columnspan=2)

        Label(f, text="Error").pack(side=LEFT)
        
        self.errnames = []
        for vn in self.ibx.varnames:
          v = self.ibx.Variable(vn)
          if np.min(v) >= 0 and np.max(v) <= 1:
            self.errnames.append(vn)

        self.errString = StringVar(f)
        self.errString.set("Select...")
        errmenu = OptionMenu(f, self.errString, *self.errnames, command=lambda value: self.newErrorVar(value, True))
        errmenu.pack(side=LEFT)

        # title1 = Label(self.master, text="Error").grid(row=4, column=0, columnspan=2)

        self.errImage = Label(self.master)
        self.errImage.grid(row=6, column=0, columnspan=2)

        f = Frame(self.master)
        f.grid(row=7, column=0, columnspan=2, sticky='ewns')

        a = Label(f, text='1D Colormap: ').pack(side=LEFT)

        self.errCmapWidget = Label(f, text='GreyScale')
        self.errCmapWidget.pack(side=LEFT)

        b = Button(f, text="...", command=self.ChooseErrorCmap)
        b.pack(side=LEFT)

        vgap = Separator(self.master, orient='vertical').grid(row=0, rowspan=6, column=3, sticky='ns')

        ResultFrame = Frame(self.master)
        ResultFrame.grid(row=0, column=4, rowspan = 8, columnspan = 3, sticky='ewns')

        upper = Frame(ResultFrame)
        upper.grid(row=0, column=4, rowspan=4, columnspan=3, sticky='ewns')

        t1 = Label(upper, text="Result")
        t1.pack(side=TOP)

        self.resultImage = Label(upper)
        self.resultImage.pack(side=TOP)

        f = Frame(upper)
        f.pack(side=TOP)

        a = Label(f, text='2D Colormap: ')
        a.pack(side=LEFT)

        self.TwoDCmapWidget = Label(f, text='GrayScale')
        self.TwoDCmapWidget.pack(side=LEFT)

        b = Button(f, text="...", command=self.Choose2DCmap)
        b.pack(side=LEFT)

        lowerRightFrame = Frame(ResultFrame, height=256)
        lowerRightFrame.grid(row=5, column=4, rowspan=4, columnspan=4, sticky='nsew')

        self.histoFrame = Frame(lowerRightFrame, width=464, height=256)
        self.histoFrame.pack(side=LEFT)

        cmapFrame = Frame(lowerRightFrame, bg='cyan', width=256, height=256)
        cmapFrame.pack(side=RIGHT, padx=2)

        self.cmap2D_image = Label(cmapFrame, bg='gray')
        self.cmap2D_image.pack(side=TOP)

        hgap = Separator(self.master, orient='horizontal')
        hgap.grid(row=9, column=0, columnspan=10, sticky='ew')

        bottombox = Frame(self.master)
        bottombox.grid(row=10, column=0, columnspan=6, sticky='ewns')
        Label(bottombox, text="Dataset Name").pack(side=LEFT)

        self.currentDataset = StringVar()
        self.currentDataset.set(ibx.names[0])

        drop = OptionMenu(bottombox, self.currentDataset, *ibx.names, command=self.selectDataset)
        drop.pack(side=LEFT)

        nxt = Button(bottombox, text='Next', command=self.next)
        nxt.pack(side=LEFT)

        prv = Button(bottombox, text='Prev', command=self.prev)
        prv.pack(side=LEFT)

        menubar = Menu(self.master)

        filemenu = Menu(menubar)
        menubar.add_cascade(label='File', menu=filemenu)
        filemenu.add_command(label='Save', command=self.Save)
        filemenu.add_command(label='Save All', command=self.SaveAll)
        filemenu.add_command(label='Quit', command=self.Quit)

        self.master.config(menu=menubar)

        self.fig = Figure(figsize = (4.5, 2.5))
        self.fig.subplots_adjust(left=0.2,
                    bottom=0.1,
                    right=0.8,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
        self.var_histo_plot1 = self.fig.add_subplot(211)
        self.err_histo_plot1 = self.fig.add_subplot(212)
        self.histo_canvas = FigureCanvasTkAgg(self.fig, self.histoFrame)
        self.histo_canvas._tkcanvas.pack(fill=BOTH)
        self.histoFrame.pack(fill=BOTH)

    def updateHistos(self):
        if self.varname:
          self.var_histo_plot1.clear()
          self.var_histo_plot1.hist(self.var.flatten(), bins=30)
        if self.errname:
          self.err_histo_plot1.clear()
          self.err_histo_plot1.hist(self.err.flatten(), bins=30)
        self.histo_canvas.draw()

    def __init__(self, ibx):
        #
        self.ibx = ibx
        self.current_index = 0
        self.varname = None
        self.errname = None
        #
        self.var = None
        self.normalized_var = None
        self.err = None
        #
        self.master = Tk()
        Frame.__init__(self, self.master)
        self.Setup()
        #
        # set up default colormaps
        #
        r = np.arange(256)/255.0
        self.varCmap = np.column_stack([r]*3)
        self.errCmap = np.column_stack([r]*3)
        r = np.arange(1024)/1023.0
        self.TwoDCmap = np.column_stack([r]*(3*1024))
        self.TwoDCmapName = 'grayscale'
        #
        # set up data
        #
        # self.newDataVar(varname, False)
        # self.newErrorVar(errname, False)
        if 'flux' in self.ibx.varnames:
          self.newDataVar('flux', False)
          self.varString.set('flux')
        if 'flux_re' in self.errnames:
          self.newErrorVar('flux_re', False)
          self.errString.set('flux_re')
        #
        self.updateTimestep(0)
        #
        # set up GUI
        #
        self.currentDataset.set(ibx.names[self.current_index])
        self.update2DCmap()
        self.updateGUI()

if len(sys.argv) != 2:
  print('syntax: %s data.ibx' % sys.argv[0])
  sys.exit(0)

ibx = IBEX.Read(sys.argv[1])
app = Application(ibx)
app.mainloop()
