#! /usr/bin/env python3

import sys, pdb
import colortools as ct
from ibex import IBEX
from PIL import Image

def syntax():
  print("syntax: %s [-s scale] data.ibx" % sys.argv[0])
  sys.exit(1)

cmap = ct.load_colormap('%s/floatpng.xml' % __file__.rsplit('/',1)[0])

scale = 1
ibx = None

args = sys.argv[1:]
while len(args) > 0:
  if args[0] == '-s':
    scale = float(args[1])
    args = args[2:]
  elif not ibx:
    ibx = IBEX.Read(args[0])
    args = args[1:]
  else:
    syntax()

if not ibx:
  syntax()

ibx.Normalize()

for i in range(len(ibx.names)):
  n,f,e = ibx.GetByIndex(i)
  rgb = cmap[(255*f).astype('i2')]
  img = Image.fromarray((255*rgb).astype('u1'))
  if scale != 0:
    img = img.resize((ibx.resolution[0]*scale, ibx.resolution[1]*scale))
  img.save('%s_F.png' % n)
