#! /usr/bin/env python3

import sys, pdb, numpy as np
from ibex import IBEX

if len(sys.argv) == 1 or sys.argv[1] == '-h':
  print("Usage: %s in.ibx" % sys.argv[0])
  sys.exit(1)

idata = sys.argv[1]

ibex = IBEX.Read(sys.argv[1])
for v in ibex.varnames:
  print(v)


